name: VPS with Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: نصب و پیکربندی SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server pwgen
          PASS=$(pwgen 12 1)
          echo "root:$PASS" | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh
          echo "$PASS" > password.txt

      - name: نصب cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: اجرای تونل
        run: |
          cloudflared tunnel --url ssh://localhost:22 --no-autoupdate > cf.log 2>&1 &
          sleep 10
          cat cf.log | grep -o 'https://.*trycloudflare.com' > tunnel_url.txt

      - name: ذخیره اطلاعات دسترسی
        run: |
          echo "username: root" >> tunnel_url.txt
          echo "password: $(cat password.txt)" >> tunnel_url.txt

      - name: آپلود اطلاعات به عنوان artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssh-info
          path: tunnel_url.txt
