name: SSH via tmate

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: نصب tmate و اجرای سشن
        run: |
          sudo apt update
          sudo apt install -y tmate
          tmate new-session -s main
