name: SSH via Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Expose SSH via Cloudflare
        uses: valeriangalliat/action-sshd-cloudflared@v4

      - name: خروجی دستور SSH
        run: echo "Use the ssh command printed above to connect."
