name: Free VPS with LocalXpose SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install and Configure SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl unzip
          echo 'root:pass1234' | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Download and setup LocalXpose
        run: |
          curl -L https://localxpose.io/localxpose-linux-amd64.zip -o lx.zip
          unzip lx.zip
          chmod +x localxpose

      - name: Start SSH Tunnel
        run: |
          ./localxpose tunnel tcp --port 22 --token ${{ secrets.LOCX_TOKEN }} &
          sleep 10
          echo "✅ Tunnel started. Check LocalXpose dashboard for connection info."
          echo "username: root"
          echo "password: pass1234"
          sleep 10800
