name: SSH Access via tmate

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: نصب tmate
        run: |
          sudo apt update
          sudo apt install -y tmate

      - name: اجرای نشست tmate
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇"
          tmate -S /tmp/tmate.sock display -p '# SSH:   %{tmate_ssh}'
          tmate -S /tmp/tmate.sock display -p '# WEB:   %{tmate_web}'
          echo "👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆👆"

      - name: زنده نگه داشتن Runner
        run: sleep 10800
