name: VPS with LocalXpose SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: نصب و پیکربندی SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl
          echo 'root:pass1234' | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: دانلود و نصب LocalXpose
        run: |
          curl -L https://loclx-client.s3.amazonaws.com/loclx-linux-amd64.deb -o loclx.deb
          sudo dpkg -i loclx.deb || sudo apt install -f -y  # برای رفع وابستگی

      - name: اجرای تونل TCP روی پورت 22
        run: |
          ./loclx account login ${{ secrets.LOCX_TOKEN }}
          loclx tunnel tcp --port 22 &
          sleep 10
          echo "✅ تونل فعال شد. برو به داشبورد برای دیدن آدرس."
          echo "username: root"
          echo "password: pass1234"
          sleep 10800
