name: SSH Access with tmate

on:
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: نصب tmate
        run: |
          sudo apt update
          sudo apt install -y tmate

      - name: ایجاد نشست SSH
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          tmate -S /tmp/tmate.sock display -p 'SSH دستور: %{tmate_ssh}'
          tmate -S /tmp/tmate.sock display -p 'Web آدرس: %{tmate_web}'

      - name: فعال ماندن runner برای 3 ساعت
        run: sleep 10800
