name: VPS with LocalXpose SSH (snap)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install OpenSSH Server
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          echo 'root:pass1234' | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Install LocalXpose via snap
        run: |
          sudo snap install localxpose

      - name: Authenticate and start SSH Tunnel
        run: |
          localxpose account login --token ${{ secrets.LOCX_TOKEN }}
          localxpose tunnel tcp --port 22 --to localhost:22 &
          sleep 10
          echo "✅ Tunnel started. View address in your LocalXpose dashboard under TCP tunnels."
          echo "username: root"
          echo "password: pass1234"
          sleep 10800
