name: Free VPS with LocalXpose SSH

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install and Configure SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl unzip
          echo 'root:pass1234' | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

      - name: Download LocalXpose
        run: |
          curl -s https://api.localxpose.io/api/v2/downloads/lxporx/linux/amd64 -o lx && chmod +x lx

      - name: Start SSH Tunnel
        run: |
          ./lx tunnel tcp --port 22 --token ${{ secrets.LOCX_TOKEN }} &
          sleep 10
          curl http://127.0.0.1:4040/api/tunnels | grep -Po 'tcp://\K[^\"]+'
          echo "username: root"
          echo "password: pass1234"
          sleep 10800
