name: VPS over Cloudflare Tunnel

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: ubuntu-latest

    steps:
      - name: نصب SSH و فعال‌سازی
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          echo 'root:pass1234' | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh
          sudo systemctl enable ssh

      - name: نصب cloudflared
        run: |
          wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: اجرای تونل
        run: |
          nohup cloudflared tunnel --url ssh://localhost:22 --no-autoupdate > tunnel.log 2>&1 &
          sleep 10
          cat tunnel.log | grep -o 'https://.*trycloudflare.com' || echo "⚠️ تونل ساخته نشد"
          echo "username: root"
          echo "password: pass1234"
          echo "⏳ اتصال باز می‌ماند تا 3 ساعت..."
          sleep 10800
