name: Test VPS with Cloudflare

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: نصب و راه‌اندازی SSH
        run: |
          sudo apt update
          sudo apt install -y openssh-server
          echo 'root:pass1234' | sudo chpasswd
          sudo sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh
          sudo systemctl enable ssh

      - name: نصب cloudflared
        run: |
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb

      - name: اجرای تونل با Cloudflare
        run: |
          cloudflared tunnel --url ssh://localhost:22 --no-autoupdate > tunnel.log 2>&1 &
          sleep 10
          cat tunnel.log | grep -o 'https://.*trycloudflare.com' > tunnel.txt || echo "URL not found" > tunnel.txt
          echo "username: root" >> tunnel.txt
          echo "password: pass1234" >> tunnel.txt
          cat tunnel.txt

      - name: نگه داشتن Runner زنده
        run: |
          echo "Runner is now alive for 3 hours"
          sleep 10800
